apiVersion: apps/v1
kind: Deployment
metadata:
  name: elsa
  labels:
    app: elsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elsa
  template:
    metadata:
      labels:
        app: elsa
    spec:
      containers:
      - name: elsa
        image: ${REGISTRY_URL}/elsa:$VERSION 
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: elsa-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080  # The port your Node.js app is exposed on
  selector:
    app: elsa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elsa
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elsa-service
            port:
              number: 80