apiVersion: apps/v1
kind: Deployment
metadata:
  name: elsa
  labels:
    app: elsa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elsa
  template:
    metadata:
      labels:
        app: elsa
    spec:
      containers:
      - name: elsa
        image: thanhphan1506/elsa  # You can change the Node.js version and base image here
        ports:
        - containerPort: 8080   # Your Node.js app's listening port
        env:
        - name: NODE_ENV
          value: "production"   # Environment variable for the Node.js app
        volumeMounts:
        - name: app-volume
          mountPath: /usr/src/app
        command: ["sh", "-c", "npm install && npm start"]  # You can customize this as per your app's start command
      volumes:
      - name: app-volume
        emptyDir: {}  # Alternatively, you can mount a persistent volume or config map
---
apiVersion: v1
kind: Service
metadata:
  name: elsa-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080  # The port your Node.js app is exposed on
  selector:
    app: elsa