apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SESSION_SECRET: "WW91ciBTZXNzaW9uIFNlY3JldCBnb2VzIGhlcmU="
  MAILGUN_PASSWORD: "MjllbGRkczF1cmk2"
  SMTP_PASSWORD: "aGRnZmFkc2ZhaGctLWkuZS5TZW5kZ3JpZC1hcGlrZXktLS1oZGdmYWRzZmFoZw=="
  NYT_KEY: "OTU0OGJlNmYzYTY0MTYzZDIzZTE1MzlmMDY3ZmNhYmQ6NTo2ODUzNzY0OA=="
  LASTFM_KEY: "YzhjMGVhMWM0YTZiMTk5YjM0Mjk3MjI1MTJmYmQxN2Y="
  LASTFM_SECRET: "Y2I3ODU3YjhmYmE4M2Y4MTllYTQ2Y2ExMzY4MWZlNzE="
  SNAPCHAT_SECRET: "RHlzd0NaR3l1WmwxQkJFQTF5V2xjanlBb09OQi1fcXc4V05vZGhjNGhyNA=="
  FACEBOOK_SECRET: "NDE4NjBlNThjMjU2YTNkN2FkODI2N2QzYzE5MzlhNGE="
  GITHUB_SECRET: "ODE1YWE0NjA2ZjQ3NjQ0NDY5MWM1ZjFjMTZiOWM3MGRhNjcxNGRjNg=="
  TWITTER_SECRET: "WkhhWXlLM0RRQ3F2NDlaOW9mc1lkcWlVZ2VvSUN5aDZ1b0JnRmZ1N09lWUM3d1RRSw=="
  GOOGLE_SECRET: "SmRab0lYek9IYkJhSlplY1V6cUJN"
  LINKEDIN_SECRET: "c3pkQzh0TjJzMlN1TVN5OA=="
  STEAM_KEY: "RDEyNDBERUY0RDQxRDQxNkZEMjkxRDAwNzVCNkVEM0Y="
  TWILIO_TOKEN: "YTY3MTcwZmY3YWZhMmRmM2Y0YzdkOTdjZDI0MGQwZjM="
  STRIPE_SKEY: "c2tfdGVzdF9CUW9raWtKT3ZCaUkyaExXZ0g0b2xmUTI="
  TUMBLR_SECRET: "UXBDVHNUMUlNTUNzQ0ltd2R2RmlxeUd0SVp3b3dGNW8zVVhvbmpQb05wNEhWdEpBTHQ="
  FOURSQUARE_SECRET: "VUFBQkZBV1RJSElVRkJMMFBEQzNURE1TSkpGMiRHV1BMRDNFQkRFMThFRg=="
  PAYPAL_SECRET: "RVBOMFd4QjVQYVJhdW1UQjFacEN1dVRxTHFJbEY2X0VXVWNBYlpWOTlFdTg2WWVOQlZtOUtWc3dfRXo1"
  RECAPTCHA_SECRET_KEY: "ODdlaHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4MzI5OA=="
  LOB_KEY: "dGVzdF84MTRlODkyYjE5OWQ2NWVmNmRiYjNlNGFkMjQ2ODk1NTljYQ=="
  PINTEREST_SECRET: "YjMyZjU3OGFkODNkOTRjMDU4YzY2ODIzMjkyMjBlZmRhN2U1ODE3ZTA0M2ExY2M0YTVhMWUyOGY1MWM3MDMwMQ=="
  GOOGLE_MAP_API_KEY: "Z29vZ2xlLW1hcC1hcGkta2V5"
  HERE_APP_ID: "YUh4eHh4eHh4eHh4eHh4bElnYw=="
  HERE_APP_CODE: "OWJ4eHh4eHh4eHh4eEhGRw=="
  ALPHA_VANTAGE_KEY: "YXBpLWtleQ=="
  QUICKBOOKS_CLIENT_ID: "QUJRU1h4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4bkl4aXo="
  QUICKBOOKS_CLIENT_SECRET: "S3V4M3h4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4amU1OG1xWUNk"
  TWITCH_CLIENT_ID: "a2hkeHh4eHh4eHh4eHh4eHFkcQ=="
  TWITCH_CLIENT_SECRET: "ZXhoeHh4eHh4eHh4eHh4eHh1ZG41"